---
#----------------------------------------------
# Unifi Network Controller Varibles
#----------------------------------------------
unifi_config_file: /etc/default/unifi
unifi_java_home: /usr/lib/jvm/adoptopenjdk-8-hotspot-jre-amd64
unifi_dir: "/var/lib/unifi"
unifi_mongodb_config: /etc/mongod.conf

# gpg key paths:
apt_key_path: /usr/share/keyrings
adoptopenjdk_keypath: "{{ apt_key_path }}/adoptopenjdk.gpg"
mongodb_keypath: "{{ apt_key_path }}/mongo_server_4.4.gpg"
unifi_keypath: "{{ apt_key_path }}/unifi.gpg"
#----------------------------------------------
# MondoDB Varibles
#----------------------------------------------
mongodb_version: 4.4

mongodb_repo_url: "http://repo.mongodb.org/apt/{{ ansible_distribution | lower }}/{{ mongodb_codename }}/mongodb-org/{{ mongodb_version }}{{ mongodb_multiverse }}"
mongodb_multiverse: "{{ ' multiverse' if ansible_distribution == 'Ubuntu' else '' }}"
mongodb_codename: "{{ 'buster' if ansible_distribution == 'Debian' else 'xenial' }}"
#----------------------------------------------
# UFW Firewall rules
#----------------------------------------------
ufw_logging: low
ufw_rules:
  # Ingress Ports Required for L3 Management Over the Internet
  - { port: 22, proto: tcp,  rule: allow, from_ip: any, comment: 'Port used for ssh access' }
  - { port: 3478, proto: udp,  rule: allow, from_ip: any, comment: 'Port used for STUN.' }
  - { port: 8080, proto: tcp,  rule: allow, from_ip: any, comment: 'Port used for device and controller communication' }
  - { port: 8443, proto: tcp,  rule: allow, from_ip: any, comment: 'Port used for controller GUI/API as seen in a web browser' }
  - { port: 8880, proto: tcp, rule: allow, from_ip: any, comment: 'Port used for HTTP portal redirection' }
  - { port: 8843, proto: tcp, rule: allow, from_ip: any, comment: 'Port used for HTTPS portal redirection' }
  - { port: 6789, proto: tcp, rule: allow, from_ip: any, comment: 'Port used for UniFi mobile speed test.' }
  # Local Ingress Ports
  - { port: 5514, proto: udp,  rule: allow, from_ip: any, comment: 'Port used for remote syslog capture' }
  #- { port: 5656:5699, proto: udp, rule: allow, from_ip: any, comment: 'Ports used by AP-EDU broadcasting.' }
  - { port: 10001, proto: udp, rule: allow, from_ip: any, comment: 'Port used for device discovery' }
  - { port: 1900, proto: udp, rule: allow, from_ip: any, comment: 'Port used for "Make controller discoverable on L2 network" in controller settings' }
#----------------------------------------------