---
  - name: check mongodb if gpg key exists
    stat:
      path: "{{ mongodb_keypath }}"
    register: mongodb_check

  - name: ensure the armored key is present
    get_url:
      url: https://www.mongodb.org/static/pgp/server-4.4.asc
      dest: "{{ mongodb_keypath }}_armored"
      checksum: sha256:b5b674e0fee2ff6e5f007a59bf3be522f3382f90f2c2c796e4a9b7095eb58e94

  - name: dearmor the mongodb gpg key
    shell: "gpg --dearmor < {{ mongodb_keypath }}_armored > {{ mongodb_keypath }}"
    args:
      creates: "{{ mongodb_keypath }}"

  - name: "Ensure MongoDB is present"
    apt_repository:
      repo: "deb [signed-by={{ mongodb_keypath }}] {{ mongodb_repo_url }}"
      state: present
      filename: "mongodb-{{ mongodb_version }}"
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - name: "ensure mondo db {{ mongodb_version }} is present"
    apt:
      name: mongodb-org
      state: present
      update_cache: yes

  - name: ensure the systemd service is reload and the mongod service has started
    ansible.builtin.systemd:
      state: started
      daemon_reload: yes
      name: mongod

  - name: ensure the mongod service is enabled
    ansible.builtin.systemd:
      enabled: yes
      name: mongod
